# Generated by Django 4.0.5 on 2022-06-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='user.usertype'),
        ),
    ]
